### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by nitin0301** [dwavesystems/dwave-ocean-sdk#39]
I hope this is the right place to ask about installation problems.

Getting the following error when trying to install in a new conda environment {python 3.7.5 & Mac 10.13.6}:
   
```
(Q) bash-3.2$ pip install dwave-ocean-sdk && dwave config create
Collecting dwave-ocean-sdk
  Using cached https://files.pythonhosted.org/packages/32/a8/c2bab4fc872cad9c40ecdbbefe53ad2e61c4b43709cd7ae1f481753622b4/dwave_ocean_sdk-1.5.0-py2.py3-none-any.whl
Requirement already satisfied: numpy<1.16.0 in /anaconda3/envs/Q/lib/python3.7/site-packages (from dwave-ocean-sdk) (1.15.4)
Requirement already satisfied: dwave-neal<0.6.0,>=0.5.0 in /anaconda3/envs/Q/lib/python3.7/site-packages (from dwave-ocean-sdk) (0.5.1)
Requirement already satisfied: pyqubo>=0.3.0 in /anaconda3/envs/Q/lib/python3.7/site-packages (from dwave-ocean-sdk) (0.4.0)
Collecting dwave-hybrid<0.5.0,>=0.4.0
  Using cached https://files.pythonhosted.org/packages/cc/0b/35f46bac3d06a1e703189e10d009e931754c378968cdd5c19fdf6be11e6b/dwave_hybrid-0.4.1-py2.py3-none-any.whl
Collecting dwave-tabu<0.3.0,>=0.2.0
  Using cached https://files.pythonhosted.org/packages/a8/96/81037033230e0b391472809ddf49b83f132b65e11e2b5d8c2a1212988bf6/dwave-tabu-0.2.1.tar.gz
Collecting dwavebinarycsp[mip]<0.1.0,>=0.0.9; (platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64") and python_version != "3.4"
  Using cached https://files.pythonhosted.org/packages/54/cb/3c6ed88ca888abfe62bd5f064b992831c65294904589e6ac357ea78ac492/dwavebinarycsp-0.0.12-py2.py3-none-any.whl
Requirement already satisfied: dimod<0.9.0,>=0.8.0 in /anaconda3/envs/Q/lib/python3.7/site-packages (from dwave-ocean-sdk) (0.8.18)
Requirement already satisfied: dwave-qbsolv<0.3.0,>=0.2.7 in /anaconda3/envs/Q/lib/python3.7/site-packages (from dwave-ocean-sdk) (0.2.10)
Requirement already satisfied: dwave-networkx<0.9.0,>=0.8.0 in /anaconda3/envs/Q/lib/python3.7/site-packages (from dwave-ocean-sdk) (0.8.3)
Requirement already satisfied: dwave-system<0.9.0,>=0.8.0 in /anaconda3/envs/Q/lib/python3.7/site-packages (from dwave-ocean-sdk) (0.8.0)
Requirement already satisfied: six<2.0.0,>=1.11.0 in /anaconda3/envs/Q/lib/python3.7/site-packages (from dwave-neal<0.6.0,>=0.5.0->dwave-ocean-sdk) (1.13.0)
Requirement already satisfied: minorminer>=0.1.7 in /anaconda3/envs/Q/lib/python3.7/site-packages (from dwave-hybrid<0.5.0,>=0.4.0->dwave-ocean-sdk) (0.1.9)
Requirement already satisfied: networkx in /anaconda3/envs/Q/lib/python3.7/site-packages (from dwave-hybrid<0.5.0,>=0.4.0->dwave-ocean-sdk) (2.4)
Requirement already satisfied: plucky>=0.4.3 in /anaconda3/envs/Q/lib/python3.7/site-packages (from dwave-hybrid<0.5.0,>=0.4.0->dwave-ocean-sdk) (0.4.3)
Requirement already satisfied: click>5 in /anaconda3/envs/Q/lib/python3.7/site-packages (from dwave-hybrid<0.5.0,>=0.4.0->dwave-ocean-sdk) (7.0)
Collecting penaltymodel-cache<0.5.0,>=0.4.0
  Using cached https://files.pythonhosted.org/packages/38/36/1580a020e09aff581297efd6ea58c882202ac4ef574613ee5a6709b1f2b5/penaltymodel_cache-0.4.0-py2.py3-none-any.whl
Collecting penaltymodel<0.17.0,>=0.16.0
  Using cached https://files.pythonhosted.org/packages/ec/3c/a61423b81bb178198d6670aa0d4b8f69c5d39379f8b24def4ad5595656cd/penaltymodel-0.16.2-py2.py3-none-any.whl
Collecting penaltymodel-lp<0.2.0,>=0.1.0
  Using cached https://files.pythonhosted.org/packages/f6/43/6308cb23364733689c6c25460f899e8c123c589f919eb707960abc1d8110/penaltymodel_lp-0.1.0-py3-none-any.whl
Collecting penaltymodel-mip<0.3.0,>=0.2.0; extra == "mip"
  Using cached https://files.pythonhosted.org/packages/08/ae/dcb44d5167d02addc6eef020c23e584b81540867524073d35952714192ed/penaltymodel_mip-0.2.1-py2.py3-none-any.whl
Requirement already satisfied: decorator<5.0.0,>=4.1.0 in /anaconda3/envs/Q/lib/python3.7/site-packages (from dwave-networkx<0.9.0,>=0.8.0->dwave-ocean-sdk) (4.4.1)
Requirement already satisfied: dwave-cloud-client<0.7.0,>=0.6.0 in /anaconda3/envs/Q/lib/python3.7/site-packages (from dwave-system<0.9.0,>=0.8.0->dwave-ocean-sdk) (0.6.2)
Requirement already satisfied: homebase<2.0.0,>=1.0.0 in /anaconda3/envs/Q/lib/python3.7/site-packages (from dwave-system<0.9.0,>=0.8.0->dwave-ocean-sdk) (1.0.1)
Collecting scipy<2.0.0,>=0.15.0
  Using cached https://files.pythonhosted.org/packages/43/df/3f85a3a762e5dd8d593614288c1f86a5dfbb8b20071192e850d1a9934e7d/scipy-1.3.3-cp37-cp37m-macosx_10_6_intel.whl
Collecting ortools<7.0.0,>=6.6.4659
  Using cached https://files.pythonhosted.org/packages/92/7b/bff68f6486c06181122b8a8afcd2b9632df0f4f0982cf0e7aba78bd69f84/ortools-6.10.6025-cp37-cp37m-macosx_10_13_x86_64.whl
Requirement already satisfied: requests[socks]>=2.18 in /anaconda3/envs/Q/lib/python3.7/site-packages (from dwave-cloud-client<0.7.0,>=0.6.0->dwave-system<0.9.0,>=0.8.0->dwave-ocean-sdk) (2.22.0)
Requirement already satisfied: python-dateutil>=2.7 in /anaconda3/envs/Q/lib/python3.7/site-packages (from dwave-cloud-client<0.7.0,>=0.6.0->dwave-system<0.9.0,>=0.8.0->dwave-ocean-sdk) (2.8.1)
Collecting protobuf>=3.6.1
  Using cached https://files.pythonhosted.org/packages/63/c3/c1929b176a62f2960fe8f9346bd7c3ed42dc2af7d61c0e9b21e36c68e2ce/protobuf-3.11.1-cp37-cp37m-macosx_10_9_intel.whl
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/envs/Q/lib/python3.7/site-packages (from requests[socks]>=2.18->dwave-cloud-client<0.7.0,>=0.6.0->dwave-system<0.9.0,>=0.8.0->dwave-ocean-sdk) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/envs/Q/lib/python3.7/site-packages (from requests[socks]>=2.18->dwave-cloud-client<0.7.0,>=0.6.0->dwave-system<0.9.0,>=0.8.0->dwave-ocean-sdk) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /anaconda3/envs/Q/lib/python3.7/site-packages (from requests[socks]>=2.18->dwave-cloud-client<0.7.0,>=0.6.0->dwave-system<0.9.0,>=0.8.0->dwave-ocean-sdk) (1.25.7)
Requirement already satisfied: idna<2.9,>=2.5 in /anaconda3/envs/Q/lib/python3.7/site-packages (from requests[socks]>=2.18->dwave-cloud-client<0.7.0,>=0.6.0->dwave-system<0.9.0,>=0.8.0->dwave-ocean-sdk) (2.8)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6; extra == "socks" in /anaconda3/envs/Q/lib/python3.7/site-packages (from requests[socks]>=2.18->dwave-cloud-client<0.7.0,>=0.6.0->dwave-system<0.9.0,>=0.8.0->dwave-ocean-sdk) (1.7.1)
Requirement already satisfied: setuptools in /anaconda3/envs/Q/lib/python3.7/site-packages (from protobuf>=3.6.1->ortools<7.0.0,>=6.6.4659->penaltymodel-mip<0.3.0,>=0.2.0; extra == "mip"->dwavebinarycsp[mip]<0.1.0,>=0.0.9; (platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64") and python_version != "3.4"->dwave-ocean-sdk) (42.0.2.post20191203)
Building wheels for collected packages: dwave-tabu
  Building wheel for dwave-tabu (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /anaconda3/envs/Q/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b8/202b0_l97l3dq1tmxhzhy_djd0809c/T/pip-install-1a8ezmq2/dwave-tabu/setup.py'"'"'; __file__='"'"'/private/var/folders/b8/202b0_l97l3dq1tmxhzhy_djd0809c/T/pip-install-1a8ezmq2/dwave-tabu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/b8/202b0_l97l3dq1tmxhzhy_djd0809c/T/pip-wheel-0j_brmf1 --python-tag cp37
       cwd: /private/var/folders/b8/202b0_l97l3dq1tmxhzhy_djd0809c/T/pip-install-1a8ezmq2/dwave-tabu/
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  running build_ext
  building 'tabu._tabu_search' extension
  swigging tabu/tabu_search.i to tabu/tabu_search_wrap.cpp
  swig -python -c++ -threads -o tabu/tabu_search_wrap.cpp tabu/tabu_search.i
  unable to execute 'swig': No such file or directory
  error: command 'swig' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for dwave-tabu
  Running setup.py clean for dwave-tabu
Failed to build dwave-tabu
Installing collected packages: dwave-tabu, dwave-hybrid, penaltymodel, penaltymodel-cache, scipy, penaltymodel-lp, protobuf, ortools, penaltymodel-mip, dwavebinarycsp, dwave-ocean-sdk
    Running setup.py install for dwave-tabu ... error
    ERROR: Command errored out with exit status 1:
     command: /anaconda3/envs/Q/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b8/202b0_l97l3dq1tmxhzhy_djd0809c/T/pip-install-1a8ezmq2/dwave-tabu/setup.py'"'"'; __file__='"'"'/private/var/folders/b8/202b0_l97l3dq1tmxhzhy_djd0809c/T/pip-install-1a8ezmq2/dwave-tabu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/b8/202b0_l97l3dq1tmxhzhy_djd0809c/T/pip-record-_flb0tlt/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/b8/202b0_l97l3dq1tmxhzhy_djd0809c/T/pip-install-1a8ezmq2/dwave-tabu/
    Complete output (9 lines):
    running install
    running build
    running build_py
    running build_ext
    building 'tabu._tabu_search' extension
    swigging tabu/tabu_search.i to tabu/tabu_search_wrap.cpp
    swig -python -c++ -threads -o tabu/tabu_search_wrap.cpp tabu/tabu_search.i
    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /anaconda3/envs/Q/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b8/202b0_l97l3dq1tmxhzhy_djd0809c/T/pip-install-1a8ezmq2/dwave-tabu/setup.py'"'"'; __file__='"'"'/private/var/folders/b8/202b0_l97l3dq1tmxhzhy_djd0809c/T/pip-install-1a8ezmq2/dwave-tabu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/b8/202b0_l97l3dq1tmxhzhy_djd0809c/T/pip-record-_flb0tlt/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```

**Comment by randomir** [comment]
Thank you, @nitin0301. We're working on this as part of #38.

**Comment by randomir** [comment]
This is fixed in `dwave-ocean-sdk>=1.6.0`.

**Comment by iotaisolutions** [comment]
Still getting same issue even in July 2020, please suggest the resolution

unable to execute 'swig': No such file or directory
error: Setup script exited with error: command 'swig' failed with exit status 1
